### ISSUE TITLE
[RULE] [ESLint] Ensure pointer-events: none on non-interactive pseudo-elements

### ISSUE THREAD

**Issue by oconnorjoseph** [BluMintInc/eslint-custom-rules#488]
**High-Level Overview**
Pseudo-elements (`::before`, `::after`) are often used for decorative purposes in stylesheets. However, when absolutely positioned, they can unintentionally intercept pointer events, leading to blocked interactions with underlying elements. This rule enforces adding `pointer-events: none;` to pseudo-elements unless they are explicitly meant to intercept clicks, ensuring smooth user interactions and preventing unintended UI behavior.

**Example Code (Bad vs. Good)**

_Bad Code:_  
```css
.button::before {
  content: '';
  position: absolute;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.1);
  /* Missing pointer-events: none; can block interactions */
}
```

_Good Code:_  
```css
.button::before {
  content: '';
  position: absolute;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.1);
  pointer-events: none; /* Ensures underlying elements remain interactive */
}
```

**Additional Notes**
- The rule should **only apply to pseudo-elements (`::before`, `::after`)**.
- Should **ignore cases where `pointer-events` is intentionally set to `auto`** for interactive elements (e.g., tooltips, dropdown indicators).
- Applicable to **CSS, SCSS, and styled-components**.

#### Issue:
Some pseudo-elements are meant to intercept clicks, such as custom checkboxes or tooltips.

#### Example:
```css
.custom-checkbox::before {
  content: '';
  position: absolute;
  width: 16px;
  height: 16px;
  background: blue;
  pointer-events: auto; /* Needed for interaction */
}
```

#### Solution:
- The rule should **allow** cases where `pointer-events: auto;` is explicitly set.

#### Issue:
If a project already has a global CSS rule that applies `pointer-events: none;` to all pseudo-elements, flagging each instance is redundant.

#### Solution:
- Provide an **option to ignore global rules** if they already enforce `pointer-events: none;`.

#### Issue:
Pseudo-elements that are `position: static;` or `relative;` usually do not interfere with interactions.

#### Solution:
- The rule should **only enforce `pointer-events: none;` when `position: absolute;` or `fixed;` is applied**.

#### Issue:
ESLint needs to correctly parse CSS inside template literals.

#### Example:
```jsx
const Button = styled.button`
  &::before {
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.1);
    pointer-events: none;
  }
`;
```

#### Solution:
- Ensure compatibility with **CSS-in-JS** frameworks such as styled-components and Emotion.

---
This rule improves accessibility, prevents UI bugs, and ensures developers follow best practices for pointer event handling.
